# fly.toml file generated for ffz-api-ios on 2023-04-14T17:35:16-04:00

app = "ffz-api-ios"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
